import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { Header } from 'antd/lib/layout/layout';
import Layout from 'antd/lib/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ConfigProvider
				theme={{
					token: {
						colorPrimary: '#4c16ff',
						colorInfo: '#4c16ff',
						colorTextBase: '#000000da',
					},
				}}>
				<AntdRegistry>
					<body className={inter.className}>{children}</body>
				</AntdRegistry>
			</ConfigProvider>
		</html>
	);
}
