import './main.css';

import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';

export const metadata: Metadata = {
	title: 'Digi - Dashboard',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ConfigProvider
				theme={{
					token: {
						colorPrimary: '#0000',
						colorInfo: '#4c16ff',
						colorTextBase: '#000000da',
						borderRadius: 8,
					},
				}}>
				<AntdRegistry>
					<body>{children}</body>
				</AntdRegistry>
			</ConfigProvider>
		</html>
	);
}
